# Generated by Django 6.0.1 on 2026-03-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='has_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='extras',
            field=models.ManyToManyField(blank=True, to='store.extra'),
        ),
        migrations.AddField(
            model_name='product',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.extra'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sauces',
            field=models.ManyToManyField(blank=True, to='store.sauce'),
        ),
        migrations.AddField(
            model_name='product',
            name='sauces',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.sauce'),
        ),
    ]
